### PR TITLE
Connex readme translation to Portuguese

### PR DESCRIPTION
**Pull request by renang**

### CODE REVIEW

**Comment by XJWX89** [comment]
hi @renang , thanks for contribution again . before  merging this pr , lets make the clean git history / commit history. the clean PR can  easily decipher the order of the commits in your repository. 


```sh
git remote add [name_of_repo] git@github.com:vechain/docs.git
git fetch name_of_repo
git rebase upstream/main [local_branch_name]
```
for more information please check [Github rebase](https://docs.github.com/en/get-started/using-git/about-git-rebase) / or check this [article by Catalina Turlea](https://medium.com/@catalinaturlea/clean-git-history-a-step-by-step-guide-eefc0ad8696d)

By the way , did you apply for the *VeChain Developer Academy bounty program*?  if not please checkout the [here](https://www.vechain.org/bounty-program/)

**Comment by XJWX89** [comment]
hi @renang , please let me know if you have any question .

**Comment by renang** [comment]
I'm sorry, had an emergency and had to be away for several days! Will take a look at soon as I can. Before I went away I tried a couple things with the rebase command, and wasn't successful in cleaning the history. Will try again.

Also, yes, I have applied for the bounty program, but never heard back. How does it work? What communication should I expect?

**Comment by XJWX89** [comment]
No worries, hope everything is going well for you . for the bounty program , I will check the status with my colleague and keep you posted

**Comment by renang** [comment]
Thanks for checking.

I haven't been able to figure this rebase thing out! Sorry about that. Any suggestions?

I've added the original git as one of the remotes, named it vechain, then:

`git fetch vechain`
`git rebase vechain\master`

Then it looks like there are several conflicts which I was not able to resolve.

But yes, agree that history is messy, will keep trying!

image

**Comment by renang** [comment]
Hi @XJWX89, please check history and let me know if it looks better! Thanks!

**Review by XJWX89 — APPROVED** [review]

**Pull request merged**
