### PR TITLE
Internationalization support/structure/config

### PR DESCRIPTION
**Pull request by renang**
Added support for internationalization. Added locales to config file, and created folder structure to hold possible future languages. I started with Brazilian Portuguese, and plan on translation all documentation to it.

Added new index name for algolia Portuguese locale, **vechain_pt**. I believe it has to be created within that API key, so the search does not work when on the Portuguese language, probably because the index needs to be created. If this merge is accepted I'll start working on translating the whole documentation.

### CODE REVIEW

**Comment by XJWX89** [comment]
hi @renang , thanks for the helping us to make the documents better and worldwide. I changed the structure and config ,it should be more clear and clean for you and future contributor.   please let me know if you have any questions. 

Moreover, the `index` is provided by algolia team. please remain unchanged for now , i will do some research and change the `config.js` if needed.

**Comment by renang** [comment]
Thanks @XJWX89. That makes sense. So should I pull the changes you made, or are you merging my changes? Sorry, don't do a lot of this. I had created a nav file for portuguese, and a folder for portuguese pages. You keeping those? Have a better suggestion?

**Comment by XJWX89** [comment]
hi @renang , please pull the changes I made , if you have any question please let me know , i will try my best to help you ;)

Please check below files:
- `sync/user-guide/import-ledger.md` and `sync2/faq.md` : add new guide
- `.vuepress/nav/` : i changed the structure which make `online support` in resources section and change the `tutorial` to the last.
- `config.js` 
- `/pt` folder can remain unchanged just need to make sure all the docs are the latest version (`sync/user-guide/import-ledger.md` and `sync2/faq.md`. )

**Comment by renang** [comment]
Thanks @XJWX89, I've merged the changes, added the new doc files to pt folder, added pt to the locales (not sure you want that, until all is translated, so feel free to remove it) and updated the pt nav file.

**Review by XJWX89 — APPROVED** [review]

**Pull request merged**
